### PR TITLE
Add requirements.txt

### LINKED ISSUE #1: Add requirements.txt

### PR DESCRIPTION
**Pull request by fuzzmz**
Fixes #1

### CODE REVIEW

**Comment by lari4** [comment]
need to remove unnecessary packages

**Comment by fuzzmz** [comment]
Those are dependencies of the `requests` package, I'm not sure you want them removed.

Requirements file was generated by installing the package in a clean virtualenv and freezing the reqs.

**Comment by lari4** [comment]
requests package enough

**Comment by fuzzmz** [comment]
Done.

**Pull request merged**
